# Build Angular app
FROM node:20 as build
WORKDIR /app
COPY package*.json ./
# Use npm install unless you commit a lockfile for npm ci
RUN npm install
COPY . .
RUN npm run build

# Serve with nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
# angular.json outputs to /app/dist in the build stage
COPY --from=build /app/dist/ /usr/share/nginx/html
EXPOSE 80