input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Optional: normalize fields, mask PII patterns (very basic example)
  mutate {
    gsub => ["user_name", "(?<=^.).", "*"]
  }
  # Add ECS-like fields
  mutate {
    add_field => { "event.dataset" => "bank.app" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bank-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}